baseurl: '/'
permalink: pretty
title: 'DHRIFT'

logo:
  mobile: "images/logo/DHRIFT-Logo-ltbg-tagline.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/DHRIFT-Logo-ltbg-tagline.png"
  desktop_height: "120px"
  desktop_width: "370px"
  light: "images/logo/DHRIFT-Logo-dkbg.png"

home:
  limit_services: 6

collections:
  faqs:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "faqs"
    values:
      layout: "faq"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

# plugins:
  # - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
